#!/usr/bin/env bash
HIS="${XDG_STATE_HOME:-$HOME/.local/state}/por-cli/watch.history"

RESUME=0
USE_PROXY=0
SHOW_HELP=0

while getopts "rph" opt; do
  case "$opt" in
    r) RESUME=1 ;;
    p) USE_PROXY=1 ;;
    h) SHOW_HELP=1 ;;
    *) exit 1 ;;
  esac
done

shift $((OPTIND-1))

PROXY=""
set_proxy(){
  local delay=0.05
  local spin='|/-\\'
  local i=0

  while :; do
    printf "\rLoading proxy... %c" "${spin:i++%4:1}"

    PROXY=$(curl -s https://raw.githubusercontent.com/por-cli/por-cli/refs/heads/output/https_alive.txt | shuf -n 1)

    if curl -s --fail --connect-timeout 1 --max-time 2 \
        -x "$PROXY" https://api.ipify.org >/dev/null; then
      printf "\rLoading proxy... done ✓        "
      printf "\r                               "
      printf "\r"
      return
    fi

    sleep "$delay"
  done
}

spinner() {
  local pid=$1
  local delay=0.1
  local spin='|/-\'
  while kill -0 $pid 2>/dev/null; do
    for i in $(seq 0 3); do
      printf "\r[%c] Loading..." "${spin:$i:1}"
      sleep $delay
    done
  done
  printf "\r                "
  printf "\r"
}

preview(){
  local img="$1"
  if [ -n "$TERMUX_VERSION" ]; then
    curl -s -x "$PROXY" "$img" | chafa --size=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES} -
    return
  else
    curl -s -x "$PROXY" "$img" | kitty icat --clear --transfer-mode=memory --stdin=yes --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0
    return
  fi
}

player () {
  vid="$1"
  if [ -n "$TERMUX_VERSION" ]; then
    am start -n is.xyz.mpv/is.xyz.mpv.MPVActivity -e args "--http-proxy=$PROXY" -e filepath $vid
    return
  else
    {
      mpv -fs --http-proxy="$PROXY" --msg-level=all=no $vid
    }&
  pid=$!;
  spinner "$pid";
  wait "$pid";
  return
  fi
}


get_grep(){
  OS=$(uname -s)

  if [ "$OS" = "Linux" ]; then
    grep -oP $@
  elif [ "$OS" = "Darwin" ]; then
    ggrep -oP $@
  fi
}

export -f spinner
export -f get_grep
export -f preview
export -f player


if [ "$SHOW_HELP" = "1" ] && { [ "$RESUME" = "1" ] || [ "$USE_PROXY" = "1" ]; }; then
  echo "Error: -h cannot be used with -r or -p"
  exit 1
fi

if [ "$SHOW_HELP" = "1" ]; then
  cat <<EOF
por-cli — quick search & watch helper

Usage:
  por-cli [options]

Options:
  -r            Resume & pick from history
  -p            Use proxy
  -h, --help    Show this help menu

History file:
  $HIS

Examples:
  por-cli           # interactive search (choose provider)
  por-cli -r        # resume from watch history
  por-cli -rp       # resume from watch history with a proxy
  por-cli -p        # watch with a proxy to unblock website 
  por-cli -h        # show help

EOF
exit 0
fi

# Apply proxy if requested
if [ "$USE_PROXY" = "1" ]; then
  set_proxy
fi

# Resume mode
if [ "$RESUME" = "1" ]; then

  if [ ! -s $HIS ]; then
    echo "watch a video first"
    exit 0
  fi
  cat $HIS |
    awk '!seen[$1]++' |
    fzf \
    --bind 'enter:execute(
      url={1};
      echo "$url" >> "${XDG_STATE_HOME:-$HOME/.local/state}/por-cli/watch.history";
      playlist=$(curl -sSf -x "$PROXY" --retry 20 --retry-delay 2 --retry-all-errors "$url" |
        get_grep "https://[^\\\"]+\\.m3u8" |
        head -n1 )
      bash -c "player $playlist"
      )'
      exit 0

fi


provider=`echo "xhamster spankbang eporner" | tr ' ' '\n'`
selected=`printf "$provider" | fzf`

if [[ -z $selected ]]; then
  echo "No provider selected" >&2
  exit 2
fi

if [[ $selected == "xhamster" ]]; then

  read -rp "Search: " SEARCH
  ENCODED_SEARCH=${SEARCH// /+}

  tmp=$(mktemp);
  {
      while [ -z "$PAGE" ]; do
        PAGE=$( curl -sSf -x "$PROXY" --retry 20 --retry-delay 2 --retry-all-errors --connect-timeout 10 --max-time 30 "https://xhamster1.desi/search/$ENCODED_SEARCH" 2>/dev/null|
          grep -B2 '<li class="next">' |
          get_grep 'data-page="\K\d+' |
          tail -n 1
        )
        [ -z "$PAGE" ] 
      done

      echo "$PAGE" > "$tmp"
  }&
pid=$!

spinner "$pid"
wait "$pid"
PAGE=$(cat $tmp)
rm "$tmp";
{ 
  for ((i = 1; i <= PAGE; i++)); do
    curl -sSf -x "$PROXY" --retry 20 --retry-delay 2 --retry-all-errors --connect-timeout 10 --max-time 30 https://xhamster1.desi/search/$ENCODED_SEARCH?page=$i 2>/dev/null \
      | get_grep '<a[^>]+href="https://[^"]+/videos/[^"]+"[^>]*>.*?</a>' \
      | sed -nE 's/.*href="([^"]+)".*aria-label="([^"]+)".*(data-src|src)="([^"]+\.jpg)".*/\1\t\2\t\4/p' 
    done
    notify-send -a "por-cli" "Pages loaded" "All $PAGE pages fetched. Select a video."
  } | 
    awk '!seen[$1]++' |
    fzf --delimiter=$'\t' --with-nth=2 \
    --preview 'bash -c "preview {3}"' \
    --bind "enter:execute(
      $(typeset -f spinner)
      $(typeset -f player)
      $(typeset -f get_grep)
      url='{1}';
      tmp=\$(mktemp);
      {
        echo \"\$url\" >> \"${XDG_STATE_HOME:-$HOME/.local/state}/por-cli/watch.history\";
        playlist=\"\"
        while [ -z \"\$playlist\" ]; do
          playlist=\$(curl -sSf -x \"$PROXY\" --retry 20 --retry-delay 2 --retry-all-errors \
            --connect-timeout 10 --max-time 30 \"\$url\" 2>/dev/null \
            | get_grep 'https://[^\" ]+\\.m3u8' \
            | head -n1);
          [ -z \"\$playlist\" ]
        done
        echo \"\$playlist\" > \"\$tmp\";
      } &
    pid=\$!;
    spinner \"\$pid\";
    wait \"\$pid\";
    playlist=\$(cat \"\$tmp\");
    rm \"\$tmp\";
    [ -n \"\$playlist\" ] && player \"\$playlist\"
    )"

  elif [[ $selected == "spankbang" ]]; then
    read -rp "Search: " SEARCH
    ENCODED_SEARCH=${SEARCH// /+}
    GREP_SEARCH=${ENCODED_SEARCH//+/\\+}
    tmp=$(mktemp);
    { 
      while [ -z "$PAGE" ]; do
        PAGE=$(curl -Ls -x "$PROXY"  --retry 20 --retry-delay 2 --retry-all-errors --connect-timeout 10 --max-time 30 "https://spankbang.party/s/$ENCODED_SEARCH" -A "Mozilla/5.0 (compatible; MSIE 7.01; Windows NT 5.0)" 2>/dev/null |
          get_grep "/s/$GREP_SEARCH/\K\d+(?=/)" |
          sort -n |
          tail -n1
        )

        [ -z "$PAGE" ] 
      done

      echo "$PAGE" > "$tmp"
    }&
  pid=$!

  spinner "$pid"
  wait "$pid"
  PAGE=$(cat $tmp)
  rm "$tmp";
  {
    for ((i = 1; i <= PAGE; i++)); do
      curl -Lv --retry 20 --retry-delay 2 --retry-all-errors --connect-timeout 10 --max-time 30 -x "$PROXY" "https://spankbang.party/s/$ENCODED_SEARCH/$i" -A "Mozilla/5.0 (compatible; MSIE 7.01; Windows NT 5.0)" 2>/dev/null |
        tr '\n' ' ' |
        get_grep '<div[^>]+data-testid="video-item".*?</div>\s*</div>' |
        sed -E 's|.*<img[^>]+src="([^"]+)".*?<a[^>]+href="([^"]+/video/[^"]+)".*?title="([^"]+)".*|\2\t\3\t\1|' |
        sed '1,8d' 
      done
      notify-send -a "por-cli" "Pages loaded" "All $PAGE pages fetched. Select a video."
    } | 
      fzf --delimiter=$'\t' --with-nth=2 \
      --preview 'bash -c "preview {3}"' \
      --bind "enter:execute(
        $(typeset -f spinner)
        $(typeset -f player)
        $(typeset -f get_grep)
        url=https://spankbang.party{1};
        tmp=\$(mktemp);
        {
          echo \"\$url\" >> \"\${XDG_STATE_HOME:-$HOME/.local/state}/por-cli/watch.history\";
          playlist=\"\"
          while [ -z \"\$playlist\" ]; do
            playlist=\$(curl -Lvs -x \"$PROXY\" \"\$url\" -A \"Mozilla/5.0 (compatible; MSIE 7.01; Windows NT 5.0)\" 2>/dev/null |
              tr '\n' ' ' |
              get_grep \"'m3u8'\\s*:\\s*\\[\\s*'\\K[^']+\" );
            [ -z \"\$playlist\" ]
          done
          echo \"\$playlist\" > \"\$tmp\";
        }&
      pid=\$!;
      spinner \"\$pid\";
      wait \"\$pid\";
      playlist=\$(cat \"\$tmp\");

      rm \"\$tmp\";
      [ -n \"\$playlist\" ] && player \"\$playlist\"
      )"
      exit 0
    else
      echo "WORK IN PROGRESS FOR $selected" >&2
      exit 1
fi
